apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fo-{{ .Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fo-{{ .Name }}
subjects:
- kind: ServiceAccount
  name: fo-{{ .Name }}