apiVersion: v1
kind: Service
metadata:
  name: fo-{{ .Name }}
spec:
  ports:
  - name: forward
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    kudo.dev/instance: {{ .Name }}
  sessionAffinity: None
  type: ClusterIP