apiVersion: kudo.dev/v1beta1
parameters:
  - name: replicas
    description: Number of replicas that should be run as part of the deployment
    default: 3
  - name: repository
    description: fluentd docker image repository
    default: fluentd
