apiVersion: kudo.dev/v1beta1
parameters:
  - name: replicas
    description: Number of replicas that should be run as part of the deployment
    default: 3
  - name: fluentdRepository
    description: fluentd container image repository
    default: fluentd
  - name: configmapRepository
    description: configmap-reload container image repository
    default: jimmidyson/configmap-reload
  - name: configmapTag
    description: configmap-reload container image tag
    default: v0.2.2